[2016-02-22 15:20:03] php.DEBUG: fsockopen(): unable to connect to 10.10.50.12:8000 (Connection refused) {"type":2,"file":"/home/vincent/symfony-demo/OAuthApp/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/ServerCommand.php","line":59,"level":28928} []
[2016-02-22 15:20:20] request.INFO: Matched route "homepage". {"route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://10.10.50.12:8000/"} []
[2016-02-22 15:20:20] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-02-22 15:20:20] request.INFO: Matched route "_wdt". {"route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"b19fca","_route":"_wdt"},"request_uri":"http://10.10.50.12:8000/_wdt/b19fca"} []
[2016-02-23 14:43:28] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2016-02-23 14:43:28] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2016-02-23 14:43:28] doctrine.DEBUG: CREATE TABLE client (id INT AUTO_INCREMENT NOT NULL, random_id VARCHAR(255) NOT NULL, redirect_uris LONGTEXT NOT NULL COMMENT '(DC2Type:array)', secret VARCHAR(255) NOT NULL, allowed_grant_types LONGTEXT NOT NULL COMMENT '(DC2Type:array)', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2016-02-23 14:43:29] doctrine.DEBUG: CREATE TABLE refresh_token (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_C74F21955F37A13B (token), INDEX IDX_C74F219519EB6921 (client_id), INDEX IDX_C74F2195A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2016-02-23 14:43:29] doctrine.DEBUG: CREATE TABLE auth_code (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, redirect_uri LONGTEXT NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_5933D02C5F37A13B (token), INDEX IDX_5933D02C19EB6921 (client_id), INDEX IDX_5933D02CA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2016-02-23 14:43:29] doctrine.DEBUG: CREATE TABLE acme_users (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(25) NOT NULL, email VARCHAR(25) NOT NULL, salt VARCHAR(32) NOT NULL, password VARCHAR(40) NOT NULL, is_active TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_55884A7F85E0677 (username), UNIQUE INDEX UNIQ_55884A7E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2016-02-23 14:43:30] doctrine.DEBUG: CREATE TABLE access_token (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_B6A2DD685F37A13B (token), INDEX IDX_B6A2DD6819EB6921 (client_id), INDEX IDX_B6A2DD68A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2016-02-23 14:43:30] doctrine.DEBUG: ALTER TABLE refresh_token ADD CONSTRAINT FK_C74F219519EB6921 FOREIGN KEY (client_id) REFERENCES client (id) [] []
[2016-02-23 14:43:31] doctrine.DEBUG: ALTER TABLE refresh_token ADD CONSTRAINT FK_C74F2195A76ED395 FOREIGN KEY (user_id) REFERENCES acme_users (id) [] []
[2016-02-23 14:43:31] doctrine.DEBUG: ALTER TABLE auth_code ADD CONSTRAINT FK_5933D02C19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) [] []
[2016-02-23 14:43:32] doctrine.DEBUG: ALTER TABLE auth_code ADD CONSTRAINT FK_5933D02CA76ED395 FOREIGN KEY (user_id) REFERENCES acme_users (id) [] []
[2016-02-23 14:43:32] doctrine.DEBUG: ALTER TABLE access_token ADD CONSTRAINT FK_B6A2DD6819EB6921 FOREIGN KEY (client_id) REFERENCES client (id) [] []
[2016-02-23 14:43:33] doctrine.DEBUG: ALTER TABLE access_token ADD CONSTRAINT FK_B6A2DD68A76ED395 FOREIGN KEY (user_id) REFERENCES acme_users (id) [] []
[2016-02-23 14:50:10] doctrine.DEBUG: "START TRANSACTION" [] []
[2016-02-23 14:50:10] doctrine.DEBUG: INSERT INTO client (random_id, redirect_uris, secret, allowed_grant_types) VALUES (?, ?, ?, ?) {"1":"6vwf54fea1gc0ggkoc00w008gc [...]","2":["http://client.local/"],"3":"6bzqrhxadf4s0o84gosgwo4w8k [...]","4":["authorization_code","password","refresh_token","token","client_credentials"]} []
[2016-02-23 14:50:10] doctrine.DEBUG: "COMMIT" [] []
[2016-02-23 14:52:00] php.DEBUG: fsockopen(): unable to connect to 10.10.50.12:8000 (Connection refused) {"type":2,"file":"/home/vincent/symfony-demo/OAuthApp/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/ServerCommand.php","line":59,"level":28928} []
[2016-02-23 14:52:52] php.DEBUG: fsockopen(): unable to connect to 10.10.50.12:8000 (Connection refused) {"type":2,"file":"/home/vincent/symfony-demo/OAuthApp/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/ServerCommand.php","line":59,"level":28928} []
[2016-02-23 14:52:54] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\FileLoaderLoadException: "The routing file "/home/vincent/symfony-demo/OAuthApp/app/config/routing.yml" contains unsupported keys for "acme_oauth_server_auth_login": "pattern". Expected one of: "resource", "type", "prefix", "path", "host", "schemes", "methods", "defaults", "requirements", "options", "condition" in /home/vincent/symfony-demo/OAuthApp/app/config/routing.yml (which is being imported from "/home/vincent/symfony-demo/OAuthApp/app/config/routing_dev.yml")." at /home/vincent/symfony-demo/OAuthApp/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 118 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): The routing file \"/home/vincent/symfony-demo/OAuthApp/app/config/routing.yml\" contains unsupported keys for \"acme_oauth_server_auth_login\": \"pattern\". Expected one of: \"resource\", \"type\", \"prefix\", \"path\", \"host\", \"schemes\", \"methods\", \"defaults\", \"requirements\", \"options\", \"condition\" in /home/vincent/symfony-demo/OAuthApp/app/config/routing.yml (which is being imported from \"/home/vincent/symfony-demo/OAuthApp/app/config/routing_dev.yml\"). at /home/vincent/symfony-demo/OAuthApp/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php:118, InvalidArgumentException(code: 0): The routing file \"/home/vincent/symfony-demo/OAuthApp/app/config/routing.yml\" contains unsupported keys for \"acme_oauth_server_auth_login\": \"pattern\". Expected one of: \"resource\", \"type\", \"prefix\", \"path\", \"host\", \"schemes\", \"methods\", \"defaults\", \"requirements\", \"options\", \"condition\". at /home/vincent/symfony-demo/OAuthApp/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php:183)"} []
[2016-02-23 14:57:40] php.DEBUG: fsockopen(): unable to connect to 10.10.50.12:8000 (Connection refused) {"type":2,"file":"/home/vincent/symfony-demo/OAuthApp/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/ServerCommand.php","line":59,"level":28928} []
[2016-02-23 14:57:42] request.INFO: Matched route "fos_oauth_server_token". {"route_parameters":{"_controller":"fos_oauth_server.controller.token:tokenAction","_route":"fos_oauth_server_token"},"request_uri":"http://10.10.50.12:8000/app_dev.php/oauth/v2/token?client_id=1_6vwf54fea1gc0ggkoc00w008gcwskok4o0swc0ow8w0sw44kg&client_secret=6bzqrhxadf4s0o84gosgwo4w8kko0kgc08kc48csocockssk0g&grant_type=client_credentials"} []
[2016-02-23 14:57:42] doctrine.DEBUG: SELECT t0.random_id AS random_id_1, t0.redirect_uris AS redirect_uris_2, t0.secret AS secret_3, t0.allowed_grant_types AS allowed_grant_types_4, t0.id AS id_5 FROM client t0 WHERE t0.id = ? AND t0.random_id = ? LIMIT 1 ["1","6vwf54fea1gc0ggkoc00w008gc [...]"] []
[2016-02-23 14:57:42] doctrine.DEBUG: "START TRANSACTION" [] []
[2016-02-23 14:57:42] doctrine.DEBUG: INSERT INTO access_token (token, expires_at, scope, client_id, user_id) VALUES (?, ?, ?, ?, ?) {"1":"NzU1ZjcwMGJmNzhkZmY5MzE4Yj [...]","2":1456203462,"3":"user","4":1,"5":null} []
[2016-02-23 14:57:42] doctrine.DEBUG: "COMMIT" [] []
[2016-02-23 14:58:20] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /api"" at /home/vincent/symfony-demo/OAuthApp/var/cache/dev/classes.php line 1970 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api\" at /home/vincent/symfony-demo/OAuthApp/var/cache/dev/classes.php:1970, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /home/vincent/symfony-demo/OAuthApp/var/cache/dev/appDevUrlMatcher.php:144)"} []
[2016-02-23 14:58:21] request.INFO: Matched route "_wdt". {"route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"6bb6b3","_route":"_wdt"},"request_uri":"http://10.10.50.12:8000/app_dev.php/_wdt/6bb6b3"} []
